# Generated by Django 6.0.4 on 2026-05-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group', models.IntegerField()),
                ('answer', models.IntegerField()),
                ('takeCardNumber', models.BooleanField()),
                ('takeCardCVV', models.BooleanField()),
                ('takeCardFIO', models.BooleanField()),
                ('takeCardDATA', models.BooleanField()),
            ],
        ),
    ]
