# Generated by Django 5.2.14 on 2026-05-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibertest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='group',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
