# Generated by Django 5.2.14 on 2026-05-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kibertest', '0002_rename_group_person_year_alter_person_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('id',), 'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='takeCardDATA',
        ),
        migrations.AddField(
            model_name='person',
            name='takeCardDATE',
            field=models.BooleanField(blank=True, null=True, verbose_name='Передал срок действия карты'),
        ),
        migrations.AlterField(
            model_name='person',
            name='answer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Результат теста'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='takeCardCVV',
            field=models.BooleanField(blank=True, null=True, verbose_name='Передал cvv код'),
        ),
        migrations.AlterField(
            model_name='person',
            name='takeCardFIO',
            field=models.BooleanField(blank=True, null=True, verbose_name='Передал фио из карты'),
        ),
        migrations.AlterField(
            model_name='person',
            name='takeCardNumber',
            field=models.BooleanField(blank=True, null=True, verbose_name='Передал номер карты'),
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.IntegerField(verbose_name='Курс'),
        ),
    ]
